export const products = {
  data: [
    {
      id: "prod_MmFJyxITSjpwpn",
      object: "product",
      active: true,
      attributes: [],
      created: 1668110008,
      default_price: {
        id: "price_1M2goXLGsaCGf4VkDtViCwO7",
        object: "price",
        active: true,
        billing_scheme: "per_unit",
        created: 1668110009,
        currency: "brl",
        custom_unit_amount: null,
        livemode: false,
        lookup_key: null,
        metadata: {},
        nickname: null,
        product: "prod_MmFJyxITSjpwpn",
        recurring: null,
        tax_behavior: "unspecified",
        tiers_mode: null,
        transform_quantity: null,
        type: "one_time",
        unit_amount: 990,
        unit_amount_decimal: "990",
      },
      description: "Bebida preparada com café expresso e cubos de gelo",
      images: [
        "https://files.stripe.com/links/MDB8YWNjdF8xTTJjU1JMR3NhQ0dmNFZrfGZsX3Rlc3RfTlBKeXlmYkxnMGg2TFM3WlFHNHYxQ1hk00DdS8HuUD",
      ],
      livemode: false,
      metadata: {
        categories: "tradicional,gelado",
      },
      name: "Expresso Gelado",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: null,
      type: "service",
      unit_label: null,
      updated: 1668110009,
      url: null,
    },
    {
      id: "prod_MmFHeKfvn7kvJQ",
      object: "product",
      active: true,
      attributes: [],
      created: 1668109896,
      default_price: {
        id: "price_1M2gmiLGsaCGf4Vk8gsYjE2I",
        object: "price",
        active: true,
        billing_scheme: "per_unit",
        created: 1668109896,
        currency: "brl",
        custom_unit_amount: null,
        livemode: false,
        lookup_key: null,
        metadata: {},
        nickname: null,
        product: "prod_MmFHeKfvn7kvJQ",
        recurring: null,
        tax_behavior: "unspecified",
        tiers_mode: null,
        transform_quantity: null,
        type: "one_time",
        unit_amount: 1000,
        unit_amount_decimal: "1000",
      },
      description: "Café expresso tradicional com espuma cremosa",
      images: [
        "https://files.stripe.com/links/MDB8YWNjdF8xTTJjU1JMR3NhQ0dmNFZrfGZsX3Rlc3RfcDYwcWx1ejVlRkZMNGpnVkxDelFkTGx200uOsXslEs",
      ],
      livemode: false,
      metadata: {
        categories: "tradicional",
      },
      name: "Expresso Cremoso",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: null,
      type: "service",
      unit_label: null,
      updated: 1668109897,
      url: null,
    },
    {
      id: "prod_MmFErB08ENCkso",
      object: "product",
      active: true,
      attributes: [],
      created: 1668109755,
      default_price: {
        id: "price_1M2gkSLGsaCGf4VkGdNgwcdu",
        object: "price",
        active: true,
        billing_scheme: "per_unit",
        created: 1668109756,
        currency: "brl",
        custom_unit_amount: null,
        livemode: false,
        lookup_key: null,
        metadata: {},
        nickname: null,
        product: "prod_MmFErB08ENCkso",
        recurring: null,
        tax_behavior: "unspecified",
        tiers_mode: null,
        transform_quantity: null,
        type: "one_time",
        unit_amount: 850,
        unit_amount_decimal: "850",
      },
      description: "Expresso diluído, menos intenso que o tradicional",
      images: [
        "https://files.stripe.com/links/MDB8YWNjdF8xTTJjU1JMR3NhQ0dmNFZrfGZsX3Rlc3RfNWpGV3R1cHVOYjliWWtBTDNiSnB3Z3FE00I2N6bPBr",
      ],
      livemode: false,
      metadata: {
        categories: "tradicional",
      },
      name: "Expresso Americano",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: null,
      type: "service",
      unit_label: null,
      updated: 1668109757,
      url: null,
    },
    {
      id: "prod_MmApi2e2JoZZR1",
      object: "product",
      active: true,
      attributes: [],
      created: 1668093373,
      default_price: {
        id: "price_1M2cUELGsaCGf4Vkhe5Y1eX3",
        object: "price",
        active: true,
        billing_scheme: "per_unit",
        created: 1668093374,
        currency: "brl",
        custom_unit_amount: null,
        livemode: false,
        lookup_key: null,
        metadata: {},
        nickname: null,
        product: "prod_MmApi2e2JoZZR1",
        recurring: null,
        tax_behavior: "unspecified",
        tiers_mode: null,
        transform_quantity: null,
        type: "one_time",
        unit_amount: 990,
        unit_amount_decimal: "990",
      },
      description: "O tradicional café feito com água quente e grãos moídos",
      images: [
        "https://files.stripe.com/links/MDB8YWNjdF8xTTJjU1JMR3NhQ0dmNFZrfGZsX3Rlc3RfY2VaNTljQ0RMYjE2NFJ3RFNDZGFvUHN200nK6B2PvE",
      ],
      livemode: false,
      metadata: {
        categories: "tradicional",
      },
      name: "Expresso Tradicional",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: null,
      type: "service",
      unit_label: null,
      updated: 1668109514,
      url: null,
    },
  ],
};
